version: '3.8'

services:
  api01: &api
    build: .
    hostname: api01

    ports:
      - 4000:8081

    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api
    hostname: api02

    ports:
      - 4001:8081


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1